### ISSUE TITLE
Warning in Next 14

### ISSUE THREAD

**Issue by Escalion86** [reapziq/next-yandex-metrica#11]
Next v14.0.4
next-yandex-metrica v1.1.1

`Warning: Cannot render <noscript> outside the main document. Try moving it into the root <head> tag.`

if i move to Head, then wrapper is not wrapper... functions like reachGoal is not working

layout.js
```
export default function RootLayout({ children }) {
  return (
    <html lang="ru" className="scroll-smooth">
        <body>
          <YaMetricaWrapper>
            {children}
          </YaMetricaWrapper>
        </body>
    </html>
  )
}
```

YaMetrikaWrapper.js
'use client'
```
import { YandexMetricaProvider } from 'next-yandex-metrica'

export const YaMetricaWrapper = ({ children }) => (
  <YandexMetricaProvider
    tagID={***} // my tag here
    initParameters={{
      clickmap: true,
      trackLinks: true,
      accurateTrackBounce: true,
    }}
  >
    {children}
  </YandexMetricaProvider>
)

export default YaMetricaWrapper
```

**Comment by reapziq** [comment]
Hi!
I've created a release that exposes the `ym` object, which has a signature similar to the native one.
This way, you can leave the provider in the `head` while importing `ym` directly on demand.
Let me know if that solves it for you 🙂

**Comment by reapziq** [comment]
I will close it for now. Please reopen it if you still have issues.

**Comment by di-sukharev** [comment]
i use latest nextjs with the `/app` folder, can i call `ym(id, "reachGoal", "smth")` in a BE app route? build fails when i call the `ym(.....)` in an api route:
```
> Build error occurred
Error: Failed to collect page data for /api/bot
    at /node_modules/next/dist/build/utils.js:1217:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
   Creating an optimized production build  .   Collecting page data  .error: script "build" exited with code 1
```
