### ISSUE TITLE
Rename to 'Metrika'

### ISSUE THREAD

**Issue by Poylar** [reapziq/next-yandex-metrica#14]
The name of this software comes from the russian word 'Metrika', not the english 'metrics'

**Comment by reapziq** [comment]
Hi! Thanks for the suggestion.
_Metrika_ version is already [occupied on npm](https://www.npmjs.com/package/next-yandex-metrika).
Yandex also refers to the service as "Metrica" in the English context.

![image](https://github.com/reapziq/next-yandex-metrica/assets/38317538/c7d121cf-f7d2-4eaf-bfad-11175e4e8f07)
