### ISSUE TITLE
Change md snippets

### ISSUE THREAD

**Issue by qqiwi92** [reapziq/next-yandex-metrica#15]
The code snippet in md file can be misleading, because of the name. Could you please update path to nextjs 14 app router version style?

**Comment by reapziq** [comment]
Hey!

You mean the `MyApp` naming? 🤔 
As that's what is used in [Next Pages docs](https://nextjs.org/docs/pages/building-your-application/routing/custom-app) as well

**Comment by reapziq** [comment]
Hey, I'm going to close this since there was no answer.
Feel free to reopen if there are still any questions!
