### ISSUE TITLE
Next 13

### ISSUE THREAD

**Issue by it-delta** [reapziq/next-yandex-metrica#7]
Для next 13 нужно добавить 

"use client"

в начало файла YandexMetricaProvider.tsx

**Comment by reapziq** [comment]
Боюсь что это создаст иллюзию полноценной поддержки серверных компонентов всеми эскортами пакета, хотя по факту на данный момент это не так - хуки аналитики сейчас требуют наличие клиентского провайдера (т.е. просто положить в `head` его нельзя) и используют `window` API.
Для поддержки App директории сейчас можно сделать клиентский раппер на уровне проекта, например:
```typescript
"use client";
import { YandexMetricaProvider } from 'next-yandex-metrica';

export const Analytics = ({ children }) => (
  <YandexMetricaProvider>{children}</YandexMetricaProvider>
);
```

**Comment by it-delta** [comment]
Спасибо, принято
